-- Cria o database com nome reserva_ambiente

create table cidade (
                        id integer auto_increment primary key,
                        descricao varchar(256)
);

create table endereco (
                          id integer auto_increment primary key,
                          cep text,
                          descricao text,
                          numero integer,
                          bairro text,
                          cidade_id integer,
                          foreign key (cidade_id) references cidade (id)
);

create table usuario (
                         id integer auto_increment primary key,
                         nome text,
                         data_nascimento date,
                         fone text,
                         fone2 text,
                         email text,
                         cpf text,
                         rg text,
                         username text,
                         senha text,
                         endereco_id integer,
                         foreign key (endereco_id) references endereco (id)
);

create table servidor (
                          id integer auto_increment primary key,
                          nome text,
                          data_nascimento date,
                          fone text,
                          fone2 text,
                          email text,
                          cpf text,
                          rg text,
                          siape text,
                          tipo_servidor enum ('DOCENTE', 'TAE'),
                          foto text,
                          endereco_id integer,
                          foreign key (endereco_id) references endereco (id)
);

create table curso (
                       id integer auto_increment primary key,
                       descricao text,
                       modalidade enum ('EAD', 'PRESENCIAL'),
                       periodo enum ('MATUTINO', 'VESPERTINO', 'NOTURNO'),
                       email text
);

create table coordenador (
                             id integer auto_increment primary key,
                             data_inicio date,
                             data_fim date,
                             ativo boolean,
                             servidor_id integer,
                             curso_id integer,
                             foreign key (servidor_id) references servidor (id),
                             foreign key (curso_id) references curso (id)
);

create table disciplina (
                            id integer auto_increment primary key,
                            descricao text
);

create table curso_disciplina (
                                  id integer auto_increment primary key,
                                  sigla_curso text,
                                  fase_curso integer,
                                  carga_horaria integer,
                                  curso_id integer,
                                  disciplina_id integer,
                                  docente_id integer,
                                  foreign key (curso_id) references curso (id),
                                  foreign key (disciplina_id) references disciplina (id),
                                  foreign key (docente_id) references servidor (id)
);

create table bloco (
                       id integer auto_increment primary key,
                       descricao text,
                       foto text
);

create table ambiente (
                          id integer auto_increment primary key,
                          descricao text,
                          sigla text,
                          foto text,
                          chave_acesso text,
                          bloco_id integer,
                          foreign key (bloco_id) references bloco (id)
);

insert into cidade (descricao) values ('Abdon Batista'),
                                      ('Abelardo Luz'),
                                      ('Agrolândia'),
                                      ('Agronômica'),
                                      ('Água Doce'),
                                      ('Águas de Chapecó'),
                                      ('Águas Frias'),
                                      ('Águas Mornas'),
                                      ('Alfredo Wagner'),
                                      ('Alto Bela Vista'),
                                      ('Anchieta'),
                                      ('Angelina'),
                                      ('Anita Garibaldi'),
                                      ('Anitápolis'),
                                      ('Antônio Carlos'),
                                      ('Apiúna'),
                                      ('Arabutã'),
                                      ('Araquari'),
                                      ('Araranguá'),
                                      ('Armazém'),
                                      ('Arroio Trinta'),
                                      ('Arvoredo'),
                                      ('Ascurra'),
                                      ('Atalanta'),
                                      ('Aurora'),
                                      ('Balneário Arroio do Silva'),
                                      ('Balneário Barra do Sul'),
                                      ('Balneário Camboriú'),
                                      ('Balneário Gaivota'),
                                      ('Bandeirante'),
                                      ('Barra Bonita'),
                                      ('Barra Velha'),
                                      ('Bela Vista do Toldo'),
                                      ('Belmonte'),
                                      ('Benedito Novo'),
                                      ('Biguaçu'),
                                      ('Blumenau'),
                                      ('Bocaina do Sul'),
                                      ('Bom Jardim da Serra'),
                                      ('Bom Jesus'),
                                      ('Bom Jesus do Oeste'),
                                      ('Bom Retiro'),
                                      ('Bombinhas'),
                                      ('Botuverá'),
                                      ('Braço do Norte'),
                                      ('Braço do Trombudo'),
                                      ('Brunópolis'),
                                      ('Brusque'),
                                      ('Caçador'),
                                      ('Caibi'),
                                      ('Calmon'),
                                      ('Camboriú'),
                                      ('Campo Alegre'),
                                      ('Campo Belo do Sul'),
                                      ('Campo Erê'),
                                      ('Campos Novos'),
                                      ('Canelinha'),
                                      ('Canoinhas'),
                                      ('Capão Alto'),
                                      ('Capinzal'),
                                      ('Capivari de Baixo'),
                                      ('Catanduvas'),
                                      ('Caxambu do Sul'),
                                      ('Celso Ramos'),
                                      ('Cerro Negro'),
                                      ('Chapadão do Lageado'),
                                      ('Chapecó'),
                                      ('Cocal do Sul'),
                                      ('Concórdia'),
                                      ('Cordilheira Alta'),
                                      ('Coronel Freitas'),
                                      ('Coronel Martins'),
                                      ('Correia Pinto'),
                                      ('Corupá'),
                                      ('Criciúma'),
                                      ('Cunha Porã'),
                                      ('Cunhataí'),
                                      ('Curitibanos'),
                                      ('Descanso'),
                                      ('Dionísio Cerqueira'),
                                      ('Dona Emma'),
                                      ('Doutor Pedrinho'),
                                      ('Entre Rios'),
                                      ('Ermo'),
                                      ('Erval Velho'),
                                      ('Faxinal dos Guedes'),
                                      ('Flor do Sertão'),
                                      ('Florianópolis'),
                                      ('Formosa do Sul'),
                                      ('Forquilhinha'),
                                      ('Fraiburgo'),
                                      ('Frei Rogério'),
                                      ('Galvão'),
                                      ('Garopaba'),
                                      ('Garuva'),
                                      ('Gaspar'),
                                      ('Governador Celso Ramos'),
                                      ('Grão Pará'),
                                      ('Gravatal'),
                                      ('Guabiruba'),
                                      ('Guaraciaba'),
                                      ('Guaramirim'),
                                      ('Guarujá do Sul'),
                                      ('Guatambú'),
                                      ('Herval d`Oeste'),
                                      ('Ibiam'),
                                      ('Ibicaré'),
                                      ('Ibirama'),
                                      ('Içara'),
                                      ('Ilhota'),
                                      ('Imaruí'),
                                      ('Imbituba'),
                                      ('Imbuia'),
                                      ('Indaial'),
                                      ('Iomerê'),
                                      ('Ipira'),
                                      ('Iporã do Oeste'),
                                      ('Ipuaçu'),
                                      ('Ipumirim'),
                                      ('Iraceminha'),
                                      ('Irani'),
                                      ('Irati'),
                                      ('Irineópolis'),
                                      ('Itá'),
                                      ('Itaiópolis'),
                                      ('Itajaí'),
                                      ('Itapema'),
                                      ('Itapiranga'),
                                      ('Itapoá'),
                                      ('Ituporanga'),
                                      ('Jaborá'),
                                      ('Jacinto Machado'),
                                      ('Jaguaruna'),
                                      ('Jaraguá do Sul'),
                                      ('Jardinópolis'),
                                      ('Joaçaba'),
                                      ('Joinville'),
                                      ('José Boiteux'),
                                      ('Jupiá'),
                                      ('Lacerdópolis'),
                                      ('Lages'),
                                      ('Laguna'),
                                      ('Lajeado Grande'),
                                      ('Laurentino'),
                                      ('Lauro Muller'),
                                      ('Lebon Régis'),
                                      ('Leoberto Leal'),
                                      ('Lindóia do Sul'),
                                      ('Lontras'),
                                      ('Luiz Alves'),
                                      ('Luzerna'),
                                      ('Macieira'),
                                      ('Mafra'),
                                      ('Major Gercino'),
                                      ('Major Vieira'),
                                      ('Maracajá'),
                                      ('Maravilha'),
                                      ('Marema'),
                                      ('Massaranduba'),
                                      ('Matos Costa'),
                                      ('Meleiro'),
                                      ('Mirim Doce'),
                                      ('Modelo'),
                                      ('Mondaí'),
                                      ('Monte Carlo'),
                                      ('Monte Castelo'),
                                      ('Morro da Fumaça'),
                                      ('Morro Grande'),
                                      ('Navegantes'),
                                      ('Nova Erechim'),
                                      ('Nova Itaberaba'),
                                      ('Nova Trento'),
                                      ('Nova Veneza'),
                                      ('Novo Horizonte'),
                                      ('Orleans'),
                                      ('Otacílio Costa'),
                                      ('Ouro'),
                                      ('Ouro Verde'),
                                      ('Paial'),
                                      ('Painel'),
                                      ('Palhoça'),
                                      ('Palma Sola'),
                                      ('Palmeira'),
                                      ('Palmitos'),
                                      ('Papanduva'),
                                      ('Paraíso'),
                                      ('Passo de Torres'),
                                      ('Passos Maia'),
                                      ('Paulo Lopes'),
                                      ('Pedras Grandes'),
                                      ('Penha'),
                                      ('Peritiba'),
                                      ('Petrolândia'),
                                      ('Piçarras'),
                                      ('Pinhalzinho'),
                                      ('Pinheiro Preto'),
                                      ('Piratuba'),
                                      ('Planalto Alegre'),
                                      ('Pomerode'),
                                      ('Ponte Alta'),
                                      ('Ponte Alta do Norte'),
                                      ('Ponte Serrada'),
                                      ('Porto Belo'),
                                      ('Porto União'),
                                      ('Pouso Redondo'),
                                      ('Praia Grande'),
                                      ('Presidente Castelo Branco'),
                                      ('Presidente Getúlio'),
                                      ('Presidente Nereu'),
                                      ('Princesa'),
                                      ('Quilombo'),
                                      ('Rancho Queimado'),
                                      ('Rio das Antas'),
                                      ('Rio do Campo'),
                                      ('Rio do Oeste'),
                                      ('Rio do Sul'),
                                      ('Rio dos Cedros'),
                                      ('Rio Fortuna'),
                                      ('Rio Negrinho'),
                                      ('Rio Rufino'),
                                      ('Riqueza'),
                                      ('Rodeio'),
                                      ('Romelândia'),
                                      ('Salete'),
                                      ('Saltinho'),
                                      ('Salto Veloso'),
                                      ('Sangão'),
                                      ('Santa Cecília'),
                                      ('Santa Helena'),
                                      ('Santa Rosa de Lima'),
                                      ('Santa Rosa do Sul'),
                                      ('Santa Terezinha'),
                                      ('Santa Terezinha do Progresso'),
                                      ('Santiago do Sul'),
                                      ('Santo Amaro da Imperatriz'),
                                      ('São Bento do Sul'),
                                      ('São Bernardino'),
                                      ('São Bonifácio'),
                                      ('São Carlos'),
                                      ('São Cristovão do Sul'),
                                      ('São Domingos'),
                                      ('São Francisco do Sul'),
                                      ('São João Batista'),
                                      ('São João do Itaperiú'),
                                      ('São João do Oeste'),
                                      ('São João do Sul'),
                                      ('São Joaquim'),
                                      ('São José'),
                                      ('São José do Cedro'),
                                      ('São José do Cerrito'),
                                      ('São Lourenço do Oeste'),
                                      ('São Ludgero'),
                                      ('São Martinho'),
                                      ('São Miguel da Boa Vista'),
                                      ('São Miguel do Oeste'),
                                      ('São Pedro de Alcântara'),
                                      ('Saudades'),
                                      ('Schroeder'),
                                      ('Seara'),
                                      ('Serra Alta'),
                                      ('Siderópolis'),
                                      ('Sombrio'),
                                      ('Sul Brasil'),
                                      ('Taió'),
                                      ('Tangará'),
                                      ('Tigrinhos'),
                                      ('Tijucas'),
                                      ('Timbé do Sul'),
                                      ('Timbó'),
                                      ('Timbó Grande'),
                                      ('Três Barras'),
                                      ('Treviso'),
                                      ('Treze de Maio'),
                                      ('Treze Tílias'),
                                      ('Trombudo Central'),
                                      ('Tubarão'),
                                      ('Tunápolis'),
                                      ('Turvo'),
                                      ('União do Oeste'),
                                      ('Urubici'),
                                      ('Urupema'),
                                      ('Urussanga'),
                                      ('Vargeão'),
                                      ('Vargem'),
                                      ('Vargem Bonita'),
                                      ('Vidal Ramos'),
                                      ('Videira'),
                                      ('Vitor Meireles'),
                                      ('Witmarsum'),
                                      ('Xanxerê'),
                                      ('Xavantina'),
                                      ('Xaxim'),
                                      ('Zortéa');